"""
task1/discover.py

Module phân loại và khám phá các tệp Python trong repository.

Có thể sử dụng theo hai cách:
  - Import:
        from task1.discover import scan_repo, build_dataframe, smoke_test
  - Chạy trực tiếp:
        python3 task1/discover.py
"""
import csv
import sys
import tempfile
from collections import Counter
from pathlib import Path

# Hằng số phục vụ phân loại 
TEST_DIR_KEYWORDS    = {"test", "tests"}
TEST_FILENAME_PREFIX = "test_"
SETUP_FILENAMES      = {"setup.py", "conftest.py", "__init__.py"}
AUTOGEN_DIRS         = {"build", "dist", ".egg-info"}
AUTOGEN_MARKERS      = ("auto-generated", "autogenerated", "do not edit", "do not modify")
HEADER_SCAN_LINES    = 10


def is_auto_generated(abs_path: Path) -> bool:
    """
    Kiểm tra xem tệp có phải được sinh tự động hay không.

    Trả về True nếu:
      - Nằm trong thư mục build/dist/.egg-info.
      - Phần đầu tệp chứa các marker như "DO NOT EDIT".
    """
    for part in abs_path.parts:
        if part in AUTOGEN_DIRS or part.endswith(".egg-info"):
            return True

    try:
        with open(abs_path, encoding="utf-8", errors="ignore") as fh:
            header = "".join(next(fh, "") for _ in range(HEADER_SCAN_LINES)).lower()
        return any(marker in header for marker in AUTOGEN_MARKERS)
    except OSError:
        return False


def classify_file(rel_path: Path, repo_root: Path) -> str:
    """
    Phân loại tệp Python thành một trong bốn nhóm:

        - auto-generated
        - setup
        - test
        - source

    Thứ tự ưu tiên:
        auto-generated > setup > test > source
    """
    abs_path = repo_root / rel_path
    filename = rel_path.name.lower()
    dir_parts = [p.lower() for p in rel_path.parts[:-1]]

    if is_auto_generated(abs_path):
        return "auto-generated"

    if filename in SETUP_FILENAMES:
        return "setup"

    if any(kw == p for p in dir_parts for kw in TEST_DIR_KEYWORDS):
        return "test"

    if filename.startswith(TEST_FILENAME_PREFIX):
        return "test"

    return "source"


def count_lines(abs_path: Path) -> int:
    """
    Đếm số dòng của tệp.

    Trả về -1 nếu không thể đọc tệp.
    """
    try:
        with open(abs_path, encoding="utf-8", errors="ignore") as fh:
            return sum(1 for _ in fh)
    except OSError:
        return -1


def scan_repo(repo_root: Path):
    """
    Quét toàn bộ các tệp .py trong repository.

    Trả về:
        (all_py_files_relative, categories)
    """
    all_py = sorted(repo_root.rglob("*.py"))
    all_rel = [p.relative_to(repo_root) for p in all_py]
    cats = [classify_file(p, repo_root) for p in all_rel]

    print(f"[OK] Tìm thấy {len(all_rel)} tệp .py")
    return all_rel, cats


def build_dataframe(repo_root: Path, all_py_files_relative, categories, output_dir: Path):
    """
    Tạo DataFrame từ kết quả quét và lưu ra tệp CSV.

    Trả về:
        pandas.DataFrame
    """
    import pandas as pd

    records = []

    for rel, cat in zip(all_py_files_relative, categories):
        abs_p = repo_root / rel

        records.append({
            "relative_path": str(rel).replace("\\", "/"),
            "size_bytes": abs_p.stat().st_size if abs_p.exists() else -1,
            "category": cat,
            "num_lines": count_lines(abs_p),
        })

    df = pd.DataFrame(
        records,
        columns=["relative_path", "size_bytes", "category", "num_lines"]
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    csv_path = output_dir / "discovered_files.csv"
    df.to_csv(csv_path, index=False, encoding="utf-8")

    print(f"[OK] Đã lưu tệp CSV: {csv_path} ({len(df)} dòng)")
    return df


def smoke_test():
    """
    Kiểm thử hàm is_auto_generated() với ba trường hợp:

      1. Tệp có header "DO NOT EDIT"      → True
      2. Tệp Python thông thường          → False
      3. Đường dẫn nằm trong build/       → True
    """

    # Trường hợp 1: Header chứa marker
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".py",
        delete=False,
        encoding="utf-8"
    ) as tmp:
        tmp.write("# DO NOT EDIT - auto-generated by build system.\nprint('hi')\n")
        p1 = Path(tmp.name)

    result1 = is_auto_generated(p1)
    p1.unlink()

    # Trường hợp 2: Tệp thông thường
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".py",
        delete=False,
        encoding="utf-8"
    ) as tmp:
        tmp.write("def f(): return 42\n")
        p2 = Path(tmp.name)

    result2 = is_auto_generated(p2)
    p2.unlink()

    # Trường hợp 3: Đường dẫn chứa build/
    result3 = is_auto_generated(Path("/project/build/generated.py"))

    test_cases = [
        ("Tệp có 'DO NOT EDIT'", result1, True),
        ("Tệp Python thông thường", result2, False),
        ("Đường dẫn chứa 'build/'", result3, True),
    ]

    all_ok = True

    for desc, got, expected in test_cases:
        if got == expected:
            print(f"  [OK] {desc}")
        else:
            print(f"  [LỖI] {desc} (nhận được={got}, mong đợi={expected})")
            all_ok = False

    assert all_ok, "Có ít nhất một trường hợp kiểm thử thất bại."

    print("[OK] Smoke test thành công (3/3)")


# Chạy trực tiếp 
if __name__ == "__main__":
    PROJECT_ROOT = Path(__file__).resolve().parent.parent
    REPO_ROOT = PROJECT_ROOT / "peft"
    OUTPUT_DIR = PROJECT_ROOT / "output"

    if not REPO_ROOT.exists():
        print(f"[LỖI] Không tìm thấy repository tại: {REPO_ROOT}")
        sys.exit(1)

    all_rel, cats = scan_repo(REPO_ROOT)

    counts = Counter(cats)

    print("\nKết quả phân loại:")
    for cat in ["source", "test", "setup", "auto-generated"]:
        print(f"  {cat:<20}: {counts.get(cat, 0):>5}")

    print()
    smoke_test()

    build_dataframe(REPO_ROOT, all_rel, cats, OUTPUT_DIR)

    print("\n[OK] Hoàn thành Task 1.")

